name: Generate ASCII Art

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      text:
        description: 'Text to convert to ASCII art'
        required: true
        default: 'Hello, World!'
      font:
        description: 'Font style for ASCII art'
        required: false
        default: 'standard'

jobs:
  generate-ascii:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyfiglet
      - name: Install Cowsay program
        run: ./ascii-script.sh
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y cowsay
      # - name: Execute Cowsay CMD
      #   run: |
      #     cowsay "This is a Cowsay message!"
      #     cowsay -f tux "This is a Tux Cowsay message!" >> cowsay_output.txt
      # - name: Test Cowsay Output
      #   run: |
      #     cat cowsay_output.txt