name: This demo for multijob pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Checkout the latest code
        run: echo "This is checkout job"
  InstallNode:
    runs-on: ubuntu-latest
    steps:
    - name: Install the nodejs
      uses: actions/setup-node@v5
      with:
        node-version: '18'
  InstallDependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Install the packeges
        run: npm install
  RunTests:
      runs-on: ubuntu-latest
      steps:
        - name: Run the tests
          run: npm test
  Build:
      runs-on: ubuntu-latest
      steps:
        - name: Build the project
          run: npm run build
  Deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Deploy the project
        run: echo "Deploy the project"  
  Notify:
      runs-on: ubuntu-latest
      steps:
        - name: Notify the team
          run: echo "Notify the team"
  Cleanup:
      runs-on: ubuntu-latest
      steps:
        - name: Cleanup the resources
          run: echo "Cleanup the resources"
  Finalize:
      runs-on: ubuntu-latest
      steps:
        - name: Finalize the job
          run: echo "Finalize the job"
  AllJobs:
      runs-on: ubuntu-latest
      needs: [checkout, InstallNode, InstallDependencies, RunTests, Build, Deploy, Notify, Cleanup, Finalize]
      steps:
        - name: All jobs completed
          run: echo "All jobs completed successfully"


